INSERT INTO videojuegos (titulo, formato, estado, franquicia, fecha, plataforma:actual, desarrolladora, pais, portada, trailer)VALUES
('LEGO STAR WARS THE COMPLETE SAGA', '3', '1', 'Lego', '2007', '5', 'Lucas arts', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ign.com%2Fgames%2Flego-star-wars-the-complete-saga&psig=AOvVaw2HjJOg6g9gtDL8eL0CHF6X&ust=1681253818792000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCOjO7Ne0oP4CFQAAAAAdAAAAABAD', 'https://www.youtube.com/watch?v=NkabLvecF-E'),
('NEW SUPER MARIO BROS', '1', '1', 'Mario Bros', '2006', '5', 'Nintendo', 'Japon', 'https://m.media-amazon.com/images/I/51BW6MGMY3L._AC_.jpg', 'https://www.youtube.com/watch?v=Zy41U69D6Lc'),
('LEGO INDIANA JONES THE ORIGINAL ADVENTURES', '3', '1', 'Lego', '2008', '5', 'Lucas arts', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Flegogames.fandom.com%2Fwiki%2FLEGO_Indiana_Jones%3A_The_Original_Adventures&psig=AOvVaw3oYQhIKr5LRpGS3hG7QGLJ&ust=1681460166003000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDomvGnpv4CFQAAAAAdAAAAABAK', 'https://www.youtube.com/watch?v=Qix-A8GNPfA'),
('James Cameron´s AVATAR THE GAME', '1', '1', 'Avatar', '2009', '5', 'ubisoft', 'ingles', 'Canada', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FJames-Camerons-Avatar-Game-Nintendo-DS%2Fdp%2FB002HHM11A&psig=AOvVaw1nZqK4n_RiNP_zygPpEhdn&ust=1681460308835000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMD8orWopv4CFQAAAAAdAAAAABAJ', 'NA'),
('MY ENGLISH COACH Para Hispanoparlantes', '1', '2', '', '2009', '5', 'Ubisoft', 'Ingles/latino', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com.mx%2FMy-English-Coach-Spanish-Edition-Nla%2Fdp%2FB001KL3GVS&psig=AOvVaw3sD63yoNPlNZMAjGBSgWcN&ust=1681460460066000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIDKwP2opv4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=8LPVDfXQ_9g'),
('SONIC GENERATIONS', '1', '1', 'Sonic', '2011', '6', 'SEGA', 'Ingles', 'japon', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hobbyconsolas.com%2Fvideojuegos%2Fsonic-generations&psig=AOvVaw1aRqoVy0yIZTk7b2l9Ei6M&ust=1681460602755000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDPzcGppv4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=gb9RQwlNRy8'),
('LEGO INDIANA JONES 2 THE ADVENTURE CONTINUES', '1', '1', 'Lego', '2009', '5', 'Lucas arts', 'Ingles', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.eneba.com%2Flatam%2Fsteam-lego-indiana-jones-2-the-adventure-continues-steam-key-global&psig=AOvVaw2KQfBlscb9PGRBBgJL_pk3&ust=1681485225445000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCLDW1p6Fp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=RoX4LnZaZD8'),
('TRANSFORMERS DARK OF THE MOON STEALTH FORCE EDITION', '1', '2', 'Transformers', '2011', '6', 'ACTIVISION', 'Ingles', 'Estados Unidos', "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FTransformers-Dark-Moon-Nintendo-Stealth-Force%2Fdp%2FB004N7F9SY&psig=AOvVaw2qwr7DIQSq_14wCZ5DMRw8&ust=1681485530686000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCODGl7CGp_4CFQAAAAAdAAAAABAE","https://www.youtube.com/watch?v=dokwnQ7hOxs"),
('PLANTS VS ZOMBIES', '3', '1', 'Plants Vs. Zombies', '2009', '5', 'CapCom', 'Ingles', 'Canada', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com.mx%2FPlants-Vs-Zombies-Game-Nintendo%2Fdp%2FB00407F2BQ&psig=AOvVaw2DxyOzi-jtOp7HHo_gYmpc&ust=1681485589248000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJCymMyGp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=x0dIYeFlHkc'),
('SONIC RUSH ADVENTURE', '1', '1', 'sonic', '2007', '5', 'SEGA', 'Ingles', 'Japon', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FSonic-Rush-Adventure-Nintendo-DS%2Fdp%2FB000RE50FO&psig=AOvVaw1paozI-C1Sk0SnmOX-aOBg&ust=1681487145829000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKi2rLKMp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=J4pG23S8kbA'),
('FANTASTIC FOUR RISE OF THE SILVER SURFER', '1', '1', 'Fantastic Four', '2007', '5', '2K', 'Ingles', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FFantastic-Four-Rise-Silver-Surfer%2Fdp%2FB000MK6X5O&psig=AOvVaw1NXcJIy8H881KFwxroKC5u&ust=1681487279229000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCODSkfKMp_4CFQAAAAAdAAAAABAE', 'NA'),
('BRAIN AGE Train your Brain in Minutes a Day', '1', '2', '', '2005', '5', 'TOUCH GENERATIONS', 'Ingles', 'Japon', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBrain_Age%3A_Train_Your_Brain_in_Minutes_a_Day!&psig=AOvVaw15pQMKD0O0aHBl4DFJGLez&ust=1681487409781000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKCbpbCNp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=FbJMTtCV0Ds'),
('MARIO KARD DS', '1', '1', 'Mario Bros', '2005', '5', 'Nintendo', 'Ingles', 'Japon', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com.mx%2FNintendo-Mario-Kart-DS-Racing%2Fdp%2FB000BFIASS&psig=AOvVaw0ZMhOngbTKP37Abof_vDRB&ust=1681487482052000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJDp_NWNp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=3Bx9WtQ5EMg'),
('TRANSFORMERS AUTOBOTS', '1', '1', 'Transformers', '2007', '5', 'ACTIVISION', 'Ingles', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2FTransformers-Autobots-Nintendo-DS%2Fdp%2FB000NJIV7W&psig=AOvVaw1VRMq5AlaR9vGHf_V0gHYJ&ust=1681488205212000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJDR6quQp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=bSmrEfyzWEM'),
('TRANSFORMERS DECEPTICONS', '1', '1', 'Transformers', '2007', '5', 'ACTIVISION', 'Ingles', 'Estados Unidos', 'https://m.media-amazon.com/images/I/51Wv0LkKIWL.jpg', 'https://www.youtube.com/watch?v=bSmrEfyzWEM'),
('STAR WARS THE CLONE WARS JEDI ALLIANCE', '1', '1', 'Star Wars', '2008', '5', 'Lucas arts', 'Castellano', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FStar-Wars-Clone-Jedi-Alliance-Nintendo%2Fdp%2FB001BWRBAS&psig=AOvVaw1tcF54H0VK8TTgy32WVEfe&ust=1681488322408000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIjRsuOQp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=ZPGXKAeDuSY'),
('LEGO BATTLES', '1', '1', 'Lego', '2009', '5', 'Warner Bros INTERACTIVE ENTERTRAIMENT', 'Ingles', 'Estados Unidos', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2F-%2Fes%2FLego-Battles-Nintendo-DS%2Fdp%2FB001QRJ7VY&psig=AOvVaw1W53kuGLUuxFIYLuCeCu8r&ust=1681488409085000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPDC5YyRp_4CFQAAAAAdAAAAABAE', 'https://www.youtube.com/watch?v=rGVvTqPYEYw')

INSERT INTO formato (tipo) VALUES
('digital'),
('físico'),
('ambos');

INSERT INTO estado (tipo) VALUES
('completado'),
('jugado'),
('pendiente');

INSERT INTO franquicias (nombre, numero, numero_obtenido, año_de_estreno, desarrollador)
VALUES 
  ('NA', 0, 2, 'NA', 'NA'),
  ('lego', 85, 4, '1995', 'Travellers Tales'),
  ('mario bros', 167, 2, '1981', 'Nintendo'),
  ('sonic', 32, 2, '1991', 'sega'),
  (6, 'Transformers', '[]', 0, 0, 'NA', 'NA'),
  (7, 'Plants Bros', '[]', 0, 0, 'NA', 'NA'),
  (8, 'Sonic Bros', '[]', 0, 0, 'NA', 'NA'),
  (9, 'Fantastic Four', '[]', 0, 0, 'NA', 'NA'),
  (10, 'Star Wars', '[]', 0, 0, 'NA', 'NA');
  
INSERT INTO desarrolladora (nombre) VALUES
  ('ubisoft'),
  ('capcom'),
  ('sega'),
  ('2k'),
  ('Touch Generation'),
  ('Nintendo'),
  ('Activision'),
  ('lucasArts'),
  ('wb Interactive Entertainment');

INSERT INTO idiomas (nombre) VALUES
('Abkhaz'),
('Afar'),
('Africanos'),
('Akan'),
('Albania'),
('Amárico'),
('Árabe'),
('Aragonés'),
('Armenio'),
('Assamese'),
('Avaric'),
('Avestan'),
('Aymara'),
('Azerbaiyán'),
('Bambara'),
('Bashkir'),
('Vasco'),
('Belarús'),
('Bengalí'),
('Bihari'),
('Bislama'),
('Bosnia'),
('Breton'),
('Búlgaro'),
('Burmese'),
('Catalán'),
('Chamorro'),
('Chechenio'),
('Chichewa, Chewa, Nyanja'),
('Chino'),
('Chuvashia'),
('Cornualles'),
('Corso'),
('Cree'),
('Croacia'),
('Checo'),
('Danés'),
('Divehi, Dhivehi, Maldivas'),
('Holandés'),
('Dzongkha'),
('Inglés'),
('Esperanto'),
('Estonia'),
('Ewe'),
('Faroese'),
('Fiji'),
('Finlandés'),
('Francés'),
('Fula, Fulah, Pulaar, Pular'),
('Galicia'),
('Georgiano'),
('Alemán'),
('Griego Moderno'),
('Guaraní'),
('Gujarati'),
('Haitiano, creole haitiano'),
('Hausa'),
('Hebreo (moderno)'),
('Herero'),
('Hindi'),
('Hiri Motu'),
('Húngaro'),
('Interlingua'),
('Indonesio'),
('Interlingue'),
('Irlanda'),
('Igbo'),
('Inupiaq'),
('Ido'),
('Islandés'),
('Italiano'),
('Inuktitut'),
('Japonés'),
('Javanés'),
('Kalaallisut, Groenlandia'),
('Canarés'),
('Kanuri'),
('Cachemira'),
('Kazajstán'),
('Khmer'),
('Kikuyu, Gikuyu'),
('Kinyarwanda'),
('Kirguises, Kirguistán'),
('Komi'),
('Kongo'),
('Corea'),
('Kurdo'),
('Kwanyama, Kuanyama'),
('Latin'),
('Luxemburgués, Luxemburgués'),
('Luganda'),
('Limburgués, Limburgan, Limburger'),
('Lingala'),
('Lao'),
('Lituano'),
('Luba-Katanga'),
('Letonia'),
('Manx'),
('Macedonia'),
('Madagascar'),
('Malayo'),
('Malayalam'),
('Maltés'),
('Māori'),
('Maratí (Marathi)'),
('De las Islas Marshall'),
('Mongolia'),
('Nauru'),
('Navajo, Navaho'),
('Noruego Bokmål'),
('Ndebele del Norte'),
('Nepali'),
('Ndonga'),
('Noruego Nynorsk'),
('Noruego'),
('Nuosu'),
('Ndebele del sur'),
('Occitano'),
('Ojibwe, Ojibwa'),
('Antiguo eslavo eclesiástico, Iglesia eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo'),
('Oromo'),
('Oriya'),
('Osetia del Sur, osetio'),
('Panjabi, Punjabi'),
('Pāli'),
('Persa'),
('Polaco'),
('Portugués'),
('Quechua'),
('Romanche'),
('Kirundi'),
('Rumania, Moldavia, Moldavan'),
('Ruso'),
('Sánscrito (samskrta)'),
('Sardo'),
('Sindhi'),
('Sami del norte'),
('Samoa'),
('Sango'),
('Serbio'),
('Gaélico escocés, gaélico'),
('Shona'),
('Cingalés, singalés'),
('Eslovaca'),
('Esloveno'),
('Somalí'),
('Southern Sotho'),
('Español, castellano'),
('Sundanese'),
('Swahili'),
('Swati'),
('Sueco'),
('Tamil'),
('Telugu'),
('Tayikistán'),
('Tailandia'),
('Tigrinya'),
('Tibetano estándar, Tibetano, Central'),
('Turkmenistán'),
('Tagalo'),
('Tswana'),
('Tonga (Islas Tonga)'),
('Turco'),
('Tsonga'),
('Tártara'),
('Twi'),
('Tahitian'),
('Uighur, Uyghur'),
('Ucrania'),
('Urdu'),
('Uzbeko'),
('Venda'),
('Vietnamita'),
('Volapük'),
('Valonia'),
('Galés'),
('Wolof'),
('Oeste de Frisia'),
('Xhosa'),
('Yiddish'),
('Yoruba'),
('Zhuang, Chuang'),
('Zulu');

INSERT INTO plataformas (cp_id, nombre) VALUES
  ('Xbox'),
  ('Xbox 360'),
  ('Xbox One'),
  ('PlayStation 4'),
  ('Nintendo ds'),
  ('Nintendo 3ds'),
  ('Wii'),
  ('Nintendo Switch'),
  ('Steam'),
  ('Epic Games');
